### ISSUE TITLE
Bugs with Matplotlib 2.0+

### ISSUE THREAD

**Issue by jvatantollone** [aymeric-spiga/planetoplot#10]
Some of the changes brought in matplotlib 2.0+ (https://matplotlib.org/api/api_changes.html) since last year, lead to crashes and incompatibility of planetoplot...

Especially "The axisbg and axis_bgcolor properties on Axes have been deprecated in favor of facecolor." is quite annoying ...

To be short, we cannot plot anything with latest versions of mpl as long as this one (at least) is not fixed ...

**Comment by aymeric-spiga** [comment]
Thanks @jvatantollone this is great because I made a couple commits recently trying to make planetoplot compatible with latest versions, but I overlooked this axisbg problem. I removed this option. Are there other problems?

**Comment by jvatantollone** [comment]
Great it works again now !
Will let you know here if others appear.

**Comment by aymeric-spiga** [comment]
It works again but there is a problem still with basemap. A bit more difficult to fix, I have to look

**Comment by aymeric-spiga** [comment]
There is a problem with basemap, it must be updated via ``conda-forge``
It works with this setting
```
conda create -n planetoplot python=2.7
conda install numpy matplotlib netcdf4
conda install -c conda-forge basemap
```

**Comment by aymeric-spiga** [comment]
The version of ``basemap`` in conda does not work: 

> AttributeError: 'AxesSubplot' object has no attribute 'get_axis_bgcolor'

So the version of ``basemap`` must be installed with ``conda-forge`` to have the latest version where the problem is fixed
